import { canonicalJson } from "./canonical.ts";
import type {
  ContractInventory,
  ContractOperation,
  JsonSchema,
} from "./types.ts";

function pascal(value: string): string {
  const result = value.replace(
    /(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g,
    (_, _prefix, letter: string) => letter.toUpperCase(),
  );
  return /^[A-Za-z_]/.test(result) ? result : `Operation${result}`;
}

function literal(value: unknown): string {
  return JSON.stringify(value);
}

function schemaType(schema: JsonSchema | null): string {
  if (schema === null) return "null";
  if (Object.hasOwn(schema, "const")) return literal(schema.const);
  if (Array.isArray(schema.enum)) {
    return schema.enum.map(literal).join(" | ") || "never";
  }
  const unions = (schema.anyOf ?? schema.oneOf) as JsonSchema[] | undefined;
  if (unions) return unions.map(schemaType).join(" | ");
  let result: string;
  switch (schema.type) {
    case "string":
      result = "string";
      break;
    case "integer":
    case "number":
      result = "number";
      break;
    case "boolean":
      result = "boolean";
      break;
    case "null":
      result = "null";
      break;
    case "array":
      result = `readonly ${schemaType((schema.items ?? {}) as JsonSchema)}[]`;
      break;
    case "object": {
      const properties = (schema.properties ?? {}) as Record<
        string,
        JsonSchema
      >;
      const required = new Set((schema.required ?? []) as string[]);
      const fields = Object.entries(properties).sort(([a], [b]) =>
        a.localeCompare(b)
      ).map(
        ([name, child]) =>
          `readonly ${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${
            schemaType(child)
          };`,
      );
      if (
        schema.additionalProperties && schema.additionalProperties !== false
      ) {
        fields.push("readonly [key: string]: unknown;");
      }
      result = `{ ${fields.join(" ")} }`;
      break;
    }
    default:
      result = "unknown";
  }
  return schema.nullable === true ? `${result} | null` : result;
}

function inputType(operation: ContractOperation): string {
  const fields: string[] = [];
  for (const location of ["params", "query", "headers", "body"] as const) {
    const request = operation.request?.[location];
    if (request) {
      fields.push(
        `  readonly ${location === "params" ? "path" : location}: ${
          schemaType(request.schema)
        };`,
      );
    }
  }
  fields.push("  readonly signal?: AbortSignal;");
  fields.push("  readonly requestHeaders?: HeadersInit;");
  return `export interface ${pascal(operation.operationId)}Input {\n${
    fields.join("\n")
  }\n}`;
}

function responseType(operation: ContractOperation, errors: boolean): string {
  const name = `${pascal(operation.operationId)}${
    errors ? "Problem" : "Success"
  }`;
  const variants = Object.entries(operation.responses)
    .filter(([status, response]) =>
      errors
        ? response.error || Number(status) >= 400
        : !response.error && Number(status) < 400
    )
    .map(([status, response]) =>
      `{ readonly status: ${status}; readonly body: ${
        schemaType(response.schema)
      } }`
    );
  return `export type ${name} = ${variants.join(" | ") || "never"};`;
}

function operationSpec(operation: ContractOperation): string {
  const request = Object.fromEntries(
    Object.entries(operation.request ?? {}).map(([key, value]) => [
      key === "params" ? "path" : key,
      { schema: value!.schema, contentType: value!.contentType },
    ]),
  );
  return canonicalJson({
    method: operation.method,
    path: operation.path,
    request,
    responses: operation.responses,
  }).trim();
}

export function renderClient(inventory: ContractInventory): string {
  const declarations = inventory.operations.flatMap((operation) => [
    inputType(operation),
    responseType(operation, false),
    responseType(operation, true),
  ]).join("\n\n");
  const specs = inventory.operations.map((operation) =>
    `  ${JSON.stringify(operation.operationId)}: ${operationSpec(operation)}`
  ).join(",\n");
  const methods = inventory.operations.map((operation) => {
    const name = pascal(operation.operationId);
    return `    async ${
      JSON.stringify(operation.operationId)
    }(input: ${name}Input): Promise<${name}Success> {\n      return await execute(${
      JSON.stringify(operation.operationId)
    }, input as RuntimeInput, operationSpecs[${
      JSON.stringify(operation.operationId)
    }]) as ${name}Success;\n    }`;
  }).join(",\n");

  return `// Generated by Sleepy Hollow. Do not edit.
${declarations}

export interface ProblemDetails {
  readonly type: string;
  readonly title: string;
  readonly status: number;
  readonly detail?: string;
  readonly [extension: string]: unknown;
}

export class ApiError<TProblem = ProblemDetails> extends Error {
  constructor(
    readonly status: number,
    readonly operationId: string,
    readonly headers: Headers,
    readonly body: TProblem,
  ) {
    super(\`API operation \${operationId} failed with HTTP \${status}\`);
    this.name = "ApiError";
  }
}

export class ResponseContractError extends Error {
  constructor(
    readonly operationId: string,
    readonly status: number,
    readonly reason: string,
  ) {
    super(\`Response contract failed for \${operationId}: \${reason}\`);
    this.name = "ResponseContractError";
  }
}

export interface ClientOptions {
  readonly baseUrl: string;
  readonly fetch?: (request: Request) => Promise<Response>;
  readonly authenticate?: (context: { readonly operationId: string; readonly request: Request }) => Request | Promise<Request>;
  readonly responseValidation?: "off" | "error";
}

type RuntimeInput = Record<string, unknown> & { signal?: AbortSignal; requestHeaders?: HeadersInit };
type RuntimeSchema = Record<string, unknown>;
type RuntimeSpec = {
  method: string;
  path: string;
  request: Record<string, { schema: RuntimeSchema; contentType?: string }>;
  responses: Record<string, { schema: RuntimeSchema | null; contentType?: string; error?: boolean }>;
};

const operationSpecs: Record<string, RuntimeSpec> = {
${specs}
};

function matches(schema: RuntimeSchema, value: unknown): boolean {
  if (Object.hasOwn(schema, "const") && value !== schema.const) return false;
  if (Array.isArray(schema.enum) && !schema.enum.some((item) => Object.is(item, value))) return false;
  const choices = (schema.anyOf ?? schema.oneOf) as RuntimeSchema[] | undefined;
  if (choices && !choices.some((choice) => matches(choice, value))) return false;
  if (value === null) return schema.type === "null" || schema.nullable === true;
  switch (schema.type) {
    case "string": return typeof value === "string";
    case "number": return typeof value === "number" && Number.isFinite(value);
    case "integer": return typeof value === "number" && Number.isInteger(value);
    case "boolean": return typeof value === "boolean";
    case "null": return false;
    case "array": return Array.isArray(value) && value.every((item) => matches((schema.items ?? {}) as RuntimeSchema, item));
    case "object": {
      if (!value || typeof value !== "object" || Array.isArray(value)) return false;
      const record = value as Record<string, unknown>;
      const properties = (schema.properties ?? {}) as Record<string, RuntimeSchema>;
      const required = (schema.required ?? []) as string[];
      if (!required.every((name) => Object.hasOwn(record, name))) return false;
      if (!Object.entries(properties).every(([name, child]) => !Object.hasOwn(record, name) || matches(child, record[name]))) return false;
      return schema.additionalProperties !== false || Object.keys(record).every((name) => Object.hasOwn(properties, name));
    }
    default: return true;
  }
}

function applyQuery(url: URL, schema: RuntimeSchema, value: unknown): void {
  if (!value || typeof value !== "object") return;
  for (const name of Object.keys((schema.properties ?? {}) as object).sort()) {
    const item = (value as Record<string, unknown>)[name];
    if (item === undefined) continue;
    if (Array.isArray(item)) item.forEach((entry) => url.searchParams.append(name, String(entry)));
    else url.searchParams.set(name, String(item));
  }
}

export function createClient(options: ClientOptions) {
  if (!options.baseUrl) throw new TypeError("baseUrl is required");
  const baseUrl = options.baseUrl.replace(/\\/+$/, "");
  const transport = options.fetch ?? globalThis.fetch.bind(globalThis);
  const validation = options.responseValidation ?? "off";

  async function execute(operationId: string, input: RuntimeInput, spec: RuntimeSpec): Promise<unknown> {
    let route = spec.path;
    const pathValues = input.path as Record<string, unknown> | undefined;
    route = route.replace(/:([A-Za-z0-9_]+)/g, (_match, name: string) => {
      const value = pathValues?.[name];
      if (value === undefined) throw new TypeError(\`Missing path input: \${name}\`);
      return encodeURIComponent(String(value));
    });
    const url = new URL(baseUrl + route);
    if (spec.request.query) applyQuery(url, spec.request.query.schema, input.query);
    const headers = new Headers(input.requestHeaders);
    const declaredHeaders = input.headers as Record<string, unknown> | undefined;
    if (declaredHeaders) for (const [name, value] of Object.entries(declaredHeaders)) if (value !== undefined) headers.set(name, String(value));
    let body: BodyInit | undefined;
    if (spec.request.body) {
      const contentType = spec.request.body.contentType ?? "application/json";
      headers.set("content-type", contentType);
      body = contentType === "application/json" ? JSON.stringify(input.body) : String(input.body);
    }
    let request = new Request(url, { method: spec.method, headers, body, signal: input.signal });
    if (options.authenticate) request = await options.authenticate({ operationId, request });
    const response = await transport(request);
    const declared = spec.responses[String(response.status)];
    if (!declared) throw new ResponseContractError(operationId, response.status, "undeclared status");
    let parsed: unknown = null;
    if (declared.schema) {
      const expectedType = declared.contentType ?? (declared.error ? "application/problem+json" : "application/json");
      const actualType = (response.headers.get("content-type") ?? "").split(";", 1)[0].trim().toLowerCase();
      if (validation === "error" && actualType !== expectedType.toLowerCase()) {
        throw new ResponseContractError(operationId, response.status, \`expected content type \${expectedType}, received \${actualType || "none"}\`);
      }
      const text = await response.text();
      if (expectedType.toLowerCase().includes("json")) {
        try {
          parsed = JSON.parse(text);
        } catch {
          throw new ResponseContractError(operationId, response.status, "malformed JSON body");
        }
      } else {
        parsed = text;
      }
      if (validation === "error" && !matches(declared.schema, parsed)) {
        throw new ResponseContractError(operationId, response.status, "body violates the declared schema");
      }
    }
    if (declared.error || response.status >= 400) throw new ApiError(response.status, operationId, response.headers, parsed as ProblemDetails);
    return { status: response.status, body: parsed };
  }

  return {
${methods}
  };
}
`;
}
