import { createHash } from "crypto";
import { join } from "path";

import { platform } from "#platform";

const OWNER = "# Generated by Sleepy Hollow. Managed deployment artifact.";
const APP = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;
const REGION = /^[a-z]{3}$/;

export type DeploymentDatabase = "sqlite" | "postgres";

export interface FlyPreparationRequest {
  readonly projectRoot: string;
  readonly target: { readonly kind: "fly"; readonly app: string };
  readonly database: DeploymentDatabase;
  readonly region?: string;
  readonly force?: boolean;
}

export interface PreparedArtifact {
  readonly path: ".dockerignore" | "Dockerfile" | "fly.toml";
  readonly digest: string;
  readonly status: "created" | "unchanged" | "updated";
}

export interface FlyPreparationResult {
  readonly schema: "sleepy-hollow-deploy-prepare-result/v1";
  readonly ok: true;
  readonly command: "deploy";
  readonly action: "prepare";
  readonly target: { readonly kind: "fly"; readonly app: string };
  readonly database: DeploymentDatabase;
  readonly region?: string;
  readonly artifacts: readonly PreparedArtifact[];
  readonly environmentKeys: readonly string[];
  readonly storage?: { readonly volume: "data"; readonly mountPath: "/data"; readonly machines: 1 };
  readonly commands: readonly string[];
}

export interface DeploymentPreparationDiagnostic {
  readonly code: string;
  readonly summary: string;
  readonly correction: string;
}

export class DeploymentPreparationError extends Error {
  readonly diagnostics: readonly DeploymentPreparationDiagnostic[];

  constructor(diagnostics: readonly DeploymentPreparationDiagnostic[]) {
    super(diagnostics[0]?.summary ?? "Deployment preparation failed.");
    this.name = "DeploymentPreparationError";
    this.diagnostics = diagnostics;
  }
}

function failure(code: string, summary: string, correction: string): never {
  throw new DeploymentPreparationError([{ code, summary, correction }]);
}

function digest(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function normalize(request: FlyPreparationRequest): Required<Pick<FlyPreparationRequest, "projectRoot" | "target" | "database">> & Pick<FlyPreparationRequest, "region" | "force"> {
  if (request.target.kind !== "fly") {
    return failure("SH_DEPLOY_TARGET_UNSUPPORTED", "Only Fly deployment preparation is supported.", "Use --target fly:<app>.");
  }
  const app = request.target.app.trim();
  if (!APP.test(app)) {
    return failure("SH_DEPLOY_TARGET_INVALID", "The Fly app name is invalid.", "Use a Fly app name containing lowercase letters, numbers, and hyphens.");
  }
  if (request.database !== "sqlite" && request.database !== "postgres") {
    return failure("SH_DEPLOY_DATABASE_INVALID", "The deployment database profile is invalid.", "Use --database sqlite or --database postgres.");
  }
  const region = request.region?.trim();
  if (request.database === "sqlite" && !region) {
    return failure("SH_DEPLOY_REGION_REQUIRED", "SQLite preparation requires a Fly region for its data volume.", "Add --region <three-letter-region>.");
  }
  if (region && !REGION.test(region)) {
    return failure("SH_DEPLOY_REGION_INVALID", "The Fly region must be a three-letter region code.", "Use a valid Fly region, such as iad.");
  }
  return {
    projectRoot: request.projectRoot,
    target: { kind: "fly", app },
    database: request.database,
    ...(region ? { region } : {}),
    ...(request.force ? { force: true } : {}),
  };
}

interface PackageManifest {
  readonly scripts?: Readonly<Record<string, unknown>>;
  readonly packageManager?: unknown;
}

async function runtime(projectRoot: string): Promise<"node" | "bun"> {
  let manifest: PackageManifest;
  try {
    manifest = JSON.parse(await platform.readTextFile(join(projectRoot, "package.json"))) as PackageManifest;
  } catch (error) {
    if (platform.isNotFound(error)) {
      return failure("SH_DEPLOY_PACKAGE_MISSING", "A deployable project must contain package.json.", "Create a Node or Bun package manifest with a start script.");
    }
    return failure("SH_DEPLOY_PACKAGE_INVALID", "package.json could not be read as JSON.", "Repair package.json and include a start script.");
  }
  if (typeof manifest.scripts?.start !== "string" || manifest.scripts.start.trim().length === 0) {
    return failure("SH_DEPLOY_START_MISSING", "A deployable project must declare a non-empty start script.", "Add scripts.start to package.json before preparing deployment.");
  }
  return typeof manifest.packageManager === "string" && manifest.packageManager.startsWith("bun@") ? "bun" : "node";
}

function dockerfile(runtime: "node" | "bun"): string {
  if (runtime === "bun") {
    return `${OWNER}\nFROM oven/bun:1.3.14\n\nWORKDIR /app\nCOPY package.json ./\nRUN bun install --production\nCOPY . .\n\nENV NODE_ENV=production\nENV PORT=3000\nEXPOSE 3000\nCMD ["bun", "run", "start"]\n`;
  }
  return `${OWNER}\nFROM node:24-bookworm-slim\n\nWORKDIR /app\nCOPY package.json ./\nRUN npm install --omit=dev\nCOPY . .\n\nENV NODE_ENV=production\nENV PORT=3000\nEXPOSE 3000\nCMD ["npm", "run", "start"]\n`;
}

function dockerignore(): string {
  return `${OWNER}\n.git\n.gitignore\nnode_modules\n.env\n.env.*\n!.env.example\n*.db\n*.sqlite\n*.sqlite3\ndata\ncoverage\ngenerated/capture.json\n`;
}

function flyToml(request: ReturnType<typeof normalize>): string {
  const shared = `${OWNER}\napp = ${quote(request.target.app)}\n${request.region ? `primary_region = ${quote(request.region)}\n` : ""}\n[http_service]\n  internal_port = 3000\n  force_https = true\n  auto_stop_machines = "stop"\n  auto_start_machines = true\n  min_machines_running = 0\n  processes = ["app"]\n\n[[http_service.checks]]\n  grace_period = "10s"\n  interval = "30s"\n  method = "GET"\n  timeout = "5s"\n  path = "/"\n`;
  if (request.database === "postgres") return shared;
  return `${shared}\n[env]\n  DATABASE_URL = "file:/data/sleepy-hollow.db"\n\n[mounts]\n  source = "data"\n  destination = "/data"\n  processes = ["app"]\n`;
}

async function read(path: string): Promise<string | undefined> {
  try {
    return await platform.readTextFile(path);
  } catch (error) {
    if (platform.isNotFound(error)) return undefined;
    throw error;
  }
}

function owned(content: string): boolean {
  return content.startsWith(`${OWNER}\n`);
}

interface PendingArtifact {
  readonly path: PreparedArtifact["path"];
  readonly content: string;
  readonly existing?: string;
  readonly status: PreparedArtifact["status"];
}

async function artifacts(request: ReturnType<typeof normalize>, projectRuntime: "node" | "bun"): Promise<PendingArtifact[]> {
  const desired: readonly Pick<PendingArtifact, "path" | "content">[] = [
    { path: ".dockerignore", content: dockerignore() },
    { path: "Dockerfile", content: dockerfile(projectRuntime) },
    { path: "fly.toml", content: flyToml(request) },
  ];
  const pending = await Promise.all(desired.map(async (item) => {
    const existing = await read(join(request.projectRoot, item.path));
    if (existing === undefined) return { ...item, status: "created" as const };
    if (existing === item.content) return { ...item, existing, status: "unchanged" as const };
    if (!owned(existing)) {
      return failure(
        "SH_DEPLOY_ARTIFACT_UNOWNED",
        `Refusing to replace unrecognized deployment artifact ${item.path}.`,
        "Move the user-owned artifact or create the managed file in a clean project.",
      );
    }
    if (!request.force) {
      return failure(
        "SH_DEPLOY_ARTIFACT_CONFLICT",
        `Managed deployment artifact ${item.path} would change.`,
        "Review the new plan and rerun with --force to replace the managed artifact.",
      );
    }
    return { ...item, existing, status: "updated" as const };
  }));
  return pending;
}

function commands(request: ReturnType<typeof normalize>): string[] {
  const app = request.target.app;
  if (request.database === "sqlite") {
    return [
      `fly apps create ${app}`,
      `fly volumes create data --app ${app} --region ${request.region}`,
      `fly deploy --app ${app}`,
    ];
  }
  return [
    `fly apps create ${app}`,
    `fly secrets set DATABASE_URL=<your-postgresql-connection-url> --app ${app}`,
    `fly deploy --app ${app}`,
  ];
}

/**
 * Creates only local Fly deployment artifacts. This function deliberately does
 * not inspect credentials, spawn a command, or contact the network.
 */
export async function prepareFlyDeployment(input: FlyPreparationRequest): Promise<FlyPreparationResult> {
  const request = normalize(input);
  const projectRuntime = await runtime(request.projectRoot);
  const pending = await artifacts(request, projectRuntime);
  for (const artifact of pending) {
    if (artifact.status !== "unchanged") {
      await platform.writeTextFile(join(request.projectRoot, artifact.path), artifact.content);
    }
  }
  return {
    schema: "sleepy-hollow-deploy-prepare-result/v1",
    ok: true,
    command: "deploy",
    action: "prepare",
    target: request.target,
    database: request.database,
    ...(request.region ? { region: request.region } : {}),
    artifacts: pending.map((artifact) => ({
      path: artifact.path,
      digest: digest(artifact.content),
      status: artifact.status,
    })),
    environmentKeys: request.database === "postgres" ? ["DATABASE_URL"] : [],
    ...(request.database === "sqlite"
      ? { storage: { volume: "data" as const, mountPath: "/data" as const, machines: 1 as const } }
      : {}),
    commands: commands(request),
  };
}

export function renderFlyPreparation(result: FlyPreparationResult): string {
  const lines = [
    `Prepared Fly deployment artifacts for ${result.target.app} (${result.database}).`,
    ...result.artifacts.map((artifact) => `  ${artifact.status.padEnd(9)} ${artifact.path} ${artifact.digest}`),
    ...(result.storage ? [`  volume     ${result.storage.volume} → ${result.storage.mountPath} (${result.storage.machines} writable Machine)`] : []),
    ...(result.environmentKeys.length ? [`  secret     ${result.environmentKeys.join(", ")}`] : []),
    "",
    "Next (run these yourself after authenticating with Fly):",
    ...result.commands.map((command) => `  ${command}`),
  ];
  return `${lines.join("\n")}\n`;
}
