import { createReadStream, existsSync, globSync, statSync } from "node:fs";
import { dirname, extname, join, normalize, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";

const here = dirname(fileURLToPath(import.meta.url));

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
};

/**
 * Serves the generated API reference during development.
 *
 * `npm run docs:api` writes the reference straight into `dist/api` after the
 * production build, which keeps 1800-odd generated files out of `public/` and
 * off the Vite copy path. The dev server has no such build step, so without
 * this the `/api/` link is live in production and dead locally — the kind of
 * mismatch that gets discovered by a visitor. Serving only, never bundled.
 */
function generatedApiReference(): Plugin {
  const root = resolve(here, "dist/api");
  return {
    name: "sleepy-hollow-api-reference",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use("/api", (request, response, next) => {
        if (!existsSync(root)) {
          response.statusCode = 503;
          response.setHeader("content-type", "text/html; charset=utf-8");
          response.end(
            "<h1>API reference not generated yet</h1><p>Run <code>npm run docs:api</code> in <code>website/</code>, " +
              "which writes it to <code>dist/api</code>. The production build does this automatically.</p>",
          );
          return;
        }

        const requested = decodeURIComponent((request.url ?? "/").split("?")[0]);
        const candidate = normalize(join(root, requested));
        if (!candidate.startsWith(root)) return next();

        const file = existsSync(candidate) && statSync(candidate).isDirectory()
          ? join(candidate, "index.html")
          : candidate;
        if (!existsSync(file) || !statSync(file).isFile()) return next();

        response.setHeader(
          "content-type",
          CONTENT_TYPES[extname(file)] ?? "application/octet-stream",
        );
        createReadStream(file).pipe(response);
      });
    },
  };
}

/**
 * Documentation entry documents are generated by `npm run docs:build`, which
 * every build, dev, and test script depends on. Discovering them here keeps the
 * published route set derived from the canonical guides rather than restated.
 */
function documentationEntries(): Record<string, string> {
  const entries: Record<string, string> = {};
  for (const absolute of globSync(resolve(here, "docs/**/index.html"))) {
    const name = relative(resolve(here, "docs"), dirname(absolute)).replaceAll(/[/\\]/g, "-");
    entries[name === "" ? "docs" : `docs-${name}`] = absolute;
  }
  return entries;
}

export default defineConfig({
  base: "/",
  plugins: [react(), generatedApiReference()],
  build: {
    outDir: "dist",
    sourcemap: false,
    rollupOptions: {
      input: {
        home: "./index.html",
        sgad: "./sgad/index.html",
        ...documentationEntries(),
      },
    },
  },
});
